### ISSUE TITLE
Way to install shared libs for downstream packages?

### ISSUE THREAD

**Issue by adriendelsalle** [pyodide/micropip#120]
Description
---

Hi!
I'm wondering if `micropip` is able to install a shared lib produced with `build: type: shared_library` in the `pyodide` recipe?

Use case: I'm trying to migrate a hello world test project for building a C++ shared lib + Python bindings using `pybind11` and `CMake` (using `scikit-build`) out of tree. It was working like a charm "in tree".

The error I get is:

```python
>>> import micropip
>>> await micropip.install(requirements="http://0.0.0.0:8080/hellopy-0.0.1-cp312-cp312-pyodide_2024_0_wasm32.whl") 
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.12/site-packages/micropip/_commands/install.py", line 176, in install
    await asyncio.gather(*wheel_promises)
  File "/lib/python3.12/site-packages/micropip/wheelinfo.py", line 121, in install
    await self._load_libraries(target)
  File "/lib/python3.12/site-packages/micropip/wheelinfo.py", line 204, in _load_libraries
    await loadDynlibsFromPackage(pkg, dynlibs)
pyodide.ffi.JsException: Error: Didn't expect to load any more file_packager files!
```
and found no way to upload the `hello-0.0.1.zip` containing the shared lib. I guess this error is produced because of the missing library.

It's quite confusing because removing the runtime dep in tree produces another misleading error
```python
>>> import hellopy
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/lib/python3.12/site-packages/hellopy/__init__.py", line 1, in <module>
    from hellopy.hellopy_core import increment
ImportError: dynamic module does not define module export function (PyInit_hellopy_core)
```
but that's another story and more related to `pyodide` main repo I guess.

Thanks!

**Comment by ryanking13** [comment]
I suggest bundling the shared library to the wheel. You can do that using `auditwheel-emscripten`.

```bash
$ pip install auditwheel-emscripten

# pillow_heif-0.8.0-cp36-abi3-pyodide_2024_0_wasm32.whl depends on libheif.so
$ pyodide auditwheel show pillow_heif-0.8.0-cp36-abi3-pyodide_2024_0_wasm32.whl
{'_pillow_heif_cffi.abi3.so': ['libheif.so']}

# libheif.so is in the directory libheif-1.12.0
$ ls libheif-1.12.0
libheif.so

# bundle libheif.so into the wheel.
$ pyodide auditwheel repair pillow_heif-0.8.0-cp36-abi3-pyodide_2024_0_wasm32.whl --libdir libheif-1.12.0
{'_pillow_heif_cffi.abi3.so': ['libheif.so'], 'pillow_heif.libs/libheif.so': []}
```

Once you've bundled the shared library in this way, you can install your package without worrying about loading the external shared library anymore.

**Comment by adriendelsalle** [comment]
@ryanking13 thanks! it works perfectly!

So maybe it's more a feature request to be able to handle pure libs to avoid embedding deps (and take benefit of smaller packages sharing libs)?

Let me know if you prefer to keep it opened or close it in favor of another issue/feat request.
Thanks again for the tip

**Comment by adriendelsalle** [comment]
I played a bit with `build: post:` to try the wheel fix but since you are already prefixed in a directory where the wheel has been unpacked, you can't directly use `pyodide auditwheel repair` there.

But `build: vendor-sharedlib: true` config is exactly what I was searching for.

**Comment by ryanking13** [comment]
> So maybe it's more a feature request to be able to handle pure libs to avoid embedding deps (and take benefit of smaller packages sharing libs)?

We're interested in that, but we're still trying to figure out how to make it easy to use. It's something that needs to be handled in https://github.com/pyodide/pyodide-lock
