### ISSUE TITLE
Verbose setting overwrite custom logger level.

### ISSUE THREAD

**Issue by Carreau** [pyodide/micropip#123]
Transcations also have a verbose attribute which is unused.

`def install(..., verbose=<value default False>)`  overwrite a custom logger level. This and a few other places should allow `None` meaning "don't change the level".

**Comment by Carreau** [comment]
(in my case it is overwritting to a lower level as I start my session with a getLogger('micropip').setLevel(DEBUG).

**Comment by ryanking13** [comment]
Thanks, that sounds reasonable to me.

I wonder if it would be better to remove the `verbose` parameter at all, and let users externally set `getLogger('micropip').setLevel()` to chang the log level. I introduced the verbose parameter to help users see what micropip does internally, but probably it is a bad practice logging-wise.

**Comment by Carreau** [comment]
Should have been fixed by #132
