### ISSUE TITLE
Retry option to recover installation failure

### ISSUE THREAD

**Issue by whitphx** [pyodide/micropip#170]
In some poor network conditions, installing packages can fail.
So retrying feature would be helpful like the [`--retries` option](https://pip.pypa.io/en/stable/cli/pip/#cmdoption-retries) of the original `pip`.

**Comment by ryanking13** [comment]
How about wrapping the whole `micropip.install` block with try/catch?

The packages that have successfully downloaded will be cached, so re-downloading the whole packages dependencies would not be a big overhead I guess.

**Comment by whitphx** [comment]
That should work, thank you!
