### ISSUE TITLE
Add python_speech_features to micropip

### ISSUE THREAD

**Issue by basicfunc** [pyodide/micropip#61]
I was trying to install the [python_speech_features](https://github.com/jameslyons/python_speech_features) package using `micropip` in `py-script`, but it seems that the package is not available in the `micropip` repository. It would be great if this package could be added to the `micropip` repository so that users could easily install it using `micropip`. It's not pure python wheel and easy to build.

**Comment by hoodmane** [comment]
There is no `micropip` repository. Micropip installs wheels from pypi. You should open an issue on python_speech_features asking them to upload a wheel to pypi.

**Comment by rth** [comment]
That repository appears unmaintained. As a workaround you can also [create the wheel yourself](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives) put it on somewhere and install it with micropip by URL.

**Comment by basicfunc** [comment]
> That repository appears unmaintained. As a workaround you can also [create the wheel yourself](https://packaging.python.org/en/latest/tutorials/packaging-projects/#generating-distribution-archives) put on somewhere and install it with micropip by URL.

Ok thanks for the info
