### ISSUE TITLE
micropip.install hangs due to network issues in workers

### ISSUE THREAD

**Issue by bugzpodder** [pyodide/micropip#76]
I am encountering an issue where micropip.install hangs due to various reasons, eg this fetching`json`:

This is done in a worker thread I believe and never happens on the main-thread.  The result is that:

await micropip.install *never* returns...

<img width="1059" alt="Screenshot 2023-08-10 at 5 57 28 PM" src="https://github.com/pyodide/micropip/assets/14841421/1d46ea26-e0ac-4d23-86fa-0cbd0e9a138a">

one of the request is from
```
https://pypi.org/pypi/seaborn/json
```

**Comment by ryanking13** [comment]
Thanks for the report @bugzpodder. Maybe adding a `timeout` parameter to micropip.install would help with what you're experiencing?

**Comment by bugzpodder** [comment]
I am not sure what the core issue was but I did some changes so that I only started installing packages from micropip when the worker has bootstraped pyodide completely, and tried to isolate the worker to running to one piece of python code at a time and I think its working now?

The strange thing is that it does seem to be browser request that never comes back and it only happens in workers.

**Comment by bugzpodder** [comment]
Actually going to reopen this.  micropip.install doesn't always hang at the fetch.  For example in my console this is the last line:

```
Loading pandas, numpy, python-dateutil, six, pytz
```
where it gets stuck and await never returns.

**Comment by bugzpodder** [comment]
Haven't seen this issue in a long time.
