### ISSUE TITLE
Transitive dependency on cryptography package

### ISSUE THREAD

**Issue by mauricelam** [pyodide/micropip#84]
My project is using Pyodide and loads in the `bumble` package via `micropip.install`, which has a transitive dependency on `cryptography`. I can load the `cryptography` package through `loadPackage()`, but when it is added as a transitive dependency in `setup.cfg` (https://github.com/google/bumble/issues/284) it fails with:

```
ValueError: Can't find a pure Python 3 wheel for 'cryptography==39'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
```

**Comment by rth** [comment]
I think it happens because the version Pyodide 0.24 includes is `39.0.2`. And so when you request `==39` it doesn't match this version tries to fetch 39 from PyPI and that doesn't have a binary wheel for WASM. So the solution is to relax the version requirement a bit instead of pinning it.

**Comment by mauricelam** [comment]
Changing the version requirement to `39.*` works perfectly. Thanks for the help!
